font_family Hurmit Nerd Font Mono
font_size 12.0

scrollback_lines 10000

strip_trailing_spaces smart

copy_on_select clipboard

hide_window_decorations yes

background_opacity 0.95

tab_bar_min_tabs 2
tab_bar_style custom
tab_title_max_length 200
tab_bar_margin_height 0 0
tab_title_template "{tab.active_wd}"
tab_separator ""
tab_bar_background #000000

enabled_layouts splits,stack,grid,tall
map ctrl+shift+l launch --location=vsplit --cwd=current
map ctrl+shift+k launch --location=hsplit --cwd=current
map ctrl+shift+space next_layout
map alt+shift+f toggle_layout stack
map alt+shift+[ move_window_backward
map alt+shift+] move_window_forward
map ctrl+shift+, move_tab_backward
map ctrl+shift+. move_tab_forward
map ctrl+shift+d detach_window ask
map ctrl+shift+' scroll_to_prompt 1
map ctrl+shift+; scroll_to_prompt -1
map ctrl+shift+enter scroll_to_prompt 0
map alt+k scroll_line_down
map alt+n scroll_line_up


# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME
